on:
  push:
    branches: [ main ]
jobs:
  transformTokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Install dependencies
      run: npm install

    - name: Transform Figma Tokens & Style Dictionary
      run: npm run build

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Tokens
  generateStorybook:
      needs: transformTokens
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Generate Storybook
        run: npm run storybook:static


