on:
  push:
    branches: [ main ]
jobs:
  transformTokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Install dependencies
      run: cd token-farm && npm install
    # Transform Figma Tokens JSON to something Style Dictionary can read
    # Create a mw-theme, exclude the global tokens
    # Create a mw-theme_dark, exclude the global tokens
    - name: Transform Figma Tokens
      run: cd token-farm && npm run transform

    - name: Create Style Dictionary
      run: cd token-farm && npm run build

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Tokens


